apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: nginx-devanshu
    image: nginx
    ports:
    - containerPort: 80
  - name: afakharany-devanshu
    image: afakharany/watcher
